### ISSUE TITLE
pip compile not working on pip 21.3

### ISSUE THREAD

**Issue by druska** [peterdemin/pip-compile-multi#290]
pip-compile-multi seems to be broken on pip==21.3 - it works on pip==21.2

The main error is: **ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (.pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/pip/_internal/utils/misc.py)**

See below for my full stack trace:
> command -v pyenv && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"
pip-compile-multi --directory . --use-cache --no-upgrade --annotate-index
Locking requirements.in to requirements.txt. References: []
ERROR executing .pyenv/versions/3.9.7/envs/myenv/bin/python3.9 -m piptools compile --no-header --verbose --emit-index-url --output-file requirements.txt requirements.in
Exit code: 1
Traceback (most recent call last):
  File ".pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/piptools/__main__.py", line 3, in <module>
    from piptools.scripts import compile, sync
  File ".pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/piptools/scripts/sync.py", line 12, in <module>
    from pip._internal.utils.misc import get_installed_distributions
**ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (.pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/pip/_internal/utils/misc.py)**

> Traceback (most recent call last):
  File ".pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File ".pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/pipcompilemulti/actions.py", line 30, in recompile
    compile_topologically(env_confs, deduplicator)
  File ".pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/pipcompilemulti/actions.py", line 39, in compile_topologically
    if env.maybe_create_lockfile():
  File ".pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File ".pyenv/versions/3.9.7/envs/myenv/lib/python3.9/site-packages/pipcompilemulti/environment.py", line 80, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
RuntimeError: Failed to pip-compile requirements.in
make: *** [compile-requirements] Error 1
